### ISSUE TITLE
ZKAPs are spent faster than the value of 1MB×month might imply

### ISSUE THREAD

**Issue by exarkun** [PrivateStorageio/ZKAPAuthorizer#215]
The lease maintenance service will renew any lease it encounters which is due to expire in 3 days or less.  Since lease renewal involves setting the lease expiration time to the current time plus 31 days, this means that the practical duration of a lease may be as small as (31 days - 3 days = ) 28 days.

This is confusing.  It is reasonable to summarize 31 days as "one month".  It is probably even reasonable to summarize 30.5 days as "one month".  28 days is not a reasonable definition of a month.

Ultimately the renewal scheme should be replaced by a system that does not throw away part of the lease period.  In the interim, we can change the lease maintenance service to let leases fully expire before renewing them.  On a system with garbage collection enabled this would be somewhat dangerous but ZKAPAuthorizer is not yet in shape to do that anyway.

**Comment by meejah** [comment]
The "danger" part is the lack of an additional 3-day buffer?

(My understanding of garbage-collection is that it won't "actually-delete" anything until an entire 31 day period of no leases happens .. that is, even if we only renew _after_ expiration and have GC turned on the capability will still be retrievable for 31 days after expiration).

**Comment by exarkun** [comment]
> The "danger" part is the lack of an additional 3-day buffer?

Yea, that's what I meant.  The increased chance that a lease will expire on a share that a user still wants.

> (My understanding of garbage-collection is that it won't "actually-delete" anything until an entire 31 day period of no leases happens .. that is, even if we only renew after expiration and have GC turned on the capability will still be retrievable for 31 days after expiration).

Okay.  That seems weird to me (which is not to say I don't believe you).  If you have a system where a client can tell a server it wants a file for 31 days then I'm not sure why the server should keep it for 62 days.  If that's what you wanted, I don't know why you wouldn't just start with a system for having a client ask the server to keep it for 62 days.  Oh well.  At some point I will have to learn more about GC in Tahoe...

**Comment by meejah** [comment]
I think that design comes from the "preservationist" mentality?

I _believe_ the idea / justification is: you can't know if some client (possibly new!) is "just about" to renew their lease and so in the interests of not surprising clients (I guess?) there's a "grace period". The grace period could be anything of course, but I think it's just "one more lease period" (so the hard-coded 31 days).

The general language around leases it that you're telling the server that some particular capability is important to you -- it does not imply "ownership" or anything by that one client.

To me it does make some amount of sense to have a grace-period -- common in "pre-paid cell phone plans" too, and domain-name registration.

Tahoe has also resisted putting in any kind of explicit "delete" functionality too .. I think on similar grounds: why should a "current" lease-holder be any more special than any other client who, after all, could have been given a read-cap out-of-band and so there's no way to know if some other client regards that data as useful (and simply hasn't been online soon enough to register a lease).

All that said, Private Storage could of course come up with their own philosophy and time-periods around this (which may require some Tahoe changes). Even then, I think some sort of grace-period still makes sense (e.g. "your account is expired; please renew in X days or all your data will actually be deleted").

**Comment by meejah** [comment]
> That seems weird to me (which is not to say I don't believe you)

Bear in mind this is just my recollection of GC / expiry -- we should 100% check the code again before making any final decisions!
