### ISSUE TITLE
`slot_testv_and_readv_and_writev` can cause denial-of-service without payment.

### ISSUE THREAD

**Issue by tomprince** [PrivateStorageio/ZKAPAuthorizer#222]
We charge users for mutable files based on the logical size of sharefiles. However, the files we actually use on disk can never shrink. In addition, users can cause those files to grow arbitrarily large without ever paying the cost for that size, by truncating the sharefile in the same call; the user is only charged for the truncated size.

**Comment by exarkun** [comment]
I guess that we could protect ourselves against this by ignoring any `length` value that shortens a share file - mirroring what the actual storage implementation does.  This means users trying to truncate shares will not be credited for the smaller file.  It's not immediately obvious that's an acceptable trade-off, I guess.

We could make the system perfectly fair by implementing share truncation in Tahoe.  I have a feeling such efforts will conflict significantly with some other efforts currently in-progress but we can just wait for those to resolve before addressing this.

I am not having much luck thinking of a third option.

**Comment by exarkun** [comment]
The implementation of `get_sharenums` / `get_write_sharenums` may be implicated here.  Or it might just be a similar, separate issue.  That function doesn't notice that non-None, non-0 `new_length` means storage is being allocated.

**Comment by exarkun** [comment]
Hm.  We can also just reject operations where there's a write beyond the point of a subsequent truncation.  I don't think the real Tahoe-LAFS client will ever do this but I guess verifying that is a good next step.

**Comment by exarkun** [comment]
Uh that was kind of easy.  The real Tahoe-LAFS client never truncates _at all_.
